Etd 166
harvard-lts/etd_dash_service pull request #1
Opened 2023-05-31 22:02 UTC by michael-lts

**Basic hello world message handoff, with docker, celery, rabbitmq **
* * *

**JIRA Ticket**: [(link)](https://jira.huit.harvard.edu/browse/ETD-166)

# What does this Pull Request do?
This is the first iteration of ETD-166 functionality: dockerize etd-dash-service, create task to listen for hello world message, and pass message on to next queue. See the README (under Running hello world example)

# How should this be tested?

Follow directions in readme to see hello world functionality

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? No 
- integration tests? No

Note, this pr is for baseline functionality, if we choose to merge into main at this point, and create additional subtasks for ETD-166. Else we can build on the branch before PR.

2023-06-01 11:49 UTC, awoods requested changes

2023-06-01 11:49 UTC, awoods commented on README.md
> +- run invoke task python script  (celery must be installed locally)
Increasingly with Docker, it seems like we can avoid installing any python tooling on our local machines. Is it possible to `exec` into the local Docker container and run the celery commands?

2023-06-01 11:49 UTC, awoods commented on README.md
> +- Known issue: dropping a message directly on the `etd_submission_ready` queue in UI not being properly read by task, nor progressing it to the next queue. Must run script.
Do we know why this issue exists?

2023-06-01 11:49 UTC, awoods commented on README.md
> +- replace rabbit connect value with dev values
@michael-lts : can you please put the ETD credentials in the ETD vault of 1Password?

2023-06-01 13:54 UTC, cgoines commented on README.md
> +- run invoke task python script  (celery must be installed locally)
also, this queue name "etd_submission_ready" is not in the .env.example.  it should be there as well. i'll also add this to the .env for the ETD-IF in the meantime.

2023-06-01 13:56 UTC, cgoines commented on README.md
> +- run invoke task python script  (celery must be installed locally)
also, the queue names "etd_submission_ready"and "etd_in_storage"  aren't in the .env.example.  the queue names needed for this component should be included there as well. i'll also add this to the .env for the ETD-IF in the meantime.

2023-06-01 16:45 UTC, ives1227 commented on README.md
> +- replace rabbit connect value with dev values
@awoods and @michael-lts I've added these to 1Password.

2023-06-01 17:59 UTC, cgoines commented on logs/etd/.gitkeep
i don't think we need to have an explicit log file for two reasons: 
1) it is breaking the tests
2) usually the log dir is specified in the dockerfile.yml or dockerfile-local.yml since it is more or less mounted externally.  
3) i don't think the other components include the log dir in their repos because of reason #2.  perhaps we should leave this out?

2023-06-01 23:51 UTC, ives1227 commented on README.md
> +- Known issue: dropping a message directly on the `etd_submission_ready` queue in UI not being properly read by task, nor progressing it to the next queue. Must run script.
@awoods I fixed this issue in the latest code and updated the readme.

2023-06-02 00:04 UTC, ives1227 commented
> i see these errors in the logs:
> 
> `2023-06-01 20:31:23,644: INFO/MainProcess] Task etd-dash-service.tasks.send_to_dash[b638e6bc-cb30-45ac-a60c-40a9034a2888] received [2023-06-01 20:31:23,693: WARNING/ForkPoolWorker-8] Hello World [2023-06-01 20:31:24,210: INFO/ForkPoolWorker-8] Task etd-dash-service.tasks.send_to_dash[b638e6bc-cb30-45ac-a60c-40a9034a2888] succeeded in 0.5253509090000534s: None [2023-06-01 20:31:58,060: WARNING/MainProcess] Received and deleted unknown message. Wrong destination?!?
> 
> The full contents of the message body was: body: '{"id": "08bd6a0c-3841-45d1-8f35-4f82e9a769b1","task": "etd-dash-service.tasks.send_to_dash","args": [{"hello":"world"}],"kwargs": {}}' (133b) {content_type:None content_encoding:None delivery_info:{'consumer_tag': 'None3', 'delivery_tag': 3, 'redelivered': False, 'exchange': '', 'routing_key': 'etd_submission_ready'} headers={}}
> 
> [2023-06-01 20:33:14,451: WARNING/MainProcess] Received and deleted unknown message. Wrong destination?!?`

These errors had to do with an improperly formatted message being placed on the queue manually.  The problem has been corrected.

2023-06-02 00:11 UTC, ives1227 commented on logs/etd/.gitkeep
I removed the explicit log file

2023-06-02 17:55 UTC, captmiddy commented on supervisord.conf
Technically SupervisorD isn't required since you are only running one process, you can just call celery on the Docker CMD and you don't need to use a secondary daemon to run this.

2023-06-02 17:59 UTC, awoods commented on supervisord.conf
That is great... and will be simplifying for all components in the ETD project.

2023-06-06 16:25 UTC, michael-lts commented on supervisord.conf
I removed supervisord

2023-06-06 16:59 UTC, ives1227 approved these changes

2023-06-06 19:05 UTC, ives1227 approved these changes

2023-06-06 19:51 UTC, cgoines approved these changes

2023-06-06 20:00 UTC, awoods approved these changes

2023-06-07 13:33 UTC, ives1227 approved these changes

2023-06-07 13:57 UTC, merged